package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"arbuga/backend/graph/model"
	"context"
	"crypto/rand"
	"errors"
	"fmt"
	"math/big"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, login string, password string) (*model.User, error) {
	rand, _ := rand.Int(rand.Reader, big.NewInt(100))

	var user *model.User
	for _, v := range r.users {
		if v.Login != nil && v.Password != nil && *v.Login == login {
			if *v.Password == password {
				user = v
			} else {
				return nil, errors.New("invalid credentials")
			}
			break
		}
	}

	if user == nil {
		user = &model.User{
			ID:         fmt.Sprintf("T%d", rand),
			Name:       "Michael" + fmt.Sprintf("T%d", rand),
			Login:      &login,
			Password:   &password, // TODO Well, you know what is wrong
			Ecosystems: []*model.Ecosystem{},
		}
		r.users = append(r.users, user)
	}
	r.me = user
	return user, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	return r.me, nil
}

// PublicEcosystems is the resolver for the publicEcosystems field.
func (r *queryResolver) PublicEcosystems(ctx context.Context) ([]*model.Ecosystem, error) {
	panic(fmt.Errorf("not implemented: PublicEcosystems - publicEcosystems"))
}

// PublicEcosystem is the resolver for the publicEcosystem field.
func (r *queryResolver) PublicEcosystem(ctx context.Context, id string) (*model.Ecosystem, error) {
	panic(fmt.Errorf("not implemented: PublicEcosystem - publicEcosystem"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
