package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"arbuga/backend/api/converters/output"
	"arbuga/backend/api/graph/model"
	"context"
	"errors"
)

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	user := ForContext(ctx)
	if user == nil {
		return nil, errors.New("not authenticated")
	}

	userFromService, err := r.UserService.GetUserById(user.ID)

	if err != nil {
		return nil, err
	}

	return output.ConvertUser(userFromService), nil
}

// Fish is the resolver for the fish field.
func (r *queryResolver) Fish(ctx context.Context) ([]*model.Fish, error) {
	fishList, err := r.FishService.SearchFishBySubstring("")

	if err != nil {
		return nil, err
	}

	return output.ConvertFishList(fishList), nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
